mongodb:
    url: mongodb://172.18.107.204:27017/frota_znh
        

server:
  port: 3009

log:
  path: var/log
  maxSize: 100000
  maxFiles: 10
  files:
    erro: monitriip-erro.log
    info: monitriip-info.log



