mysql:
  frota:
    host: localhost
    database: frota_zn4
    username: frota
    password: frota
    port: 3306

mongodb:
    url: mongodb://localhost:27017/test

server:
  port: 3009

log:
  path: var/log
  maxSize: 100000
  maxFiles: 10
  files:
    erro: monitriip-erro.log
    info: monitriip-info.log



